### ISSUE TITLE
broken links because "contributing-guide" is missing

### ISSUE THREAD

**Issue by NickleDave** [pyOpenSci/contributing-guide#78]
Hi @lwasser @choldgraf I noticed on the site when I click on the "aims and scope" and "code of conduct" links from the open-source-software-peer-review/intro.html page, I get a 404

i.e., from this page:
https://www.pyopensci.org/contributing-guide/open-source-software-peer-review/intro.html
I get a 404 from this link when I click "Aims and Scope" at the top of the page
https://www.pyopensci.org/open-source-software-peer-review/aims-and-scope.html
but I can get to it directly when I click on the link in the sidebar:
https://www.pyopensci.org/contributing-guide/open-source-software-peer-review/aims-and-scope.html

Is it an issue with how `table-of-contents` gets parsed, which seems to be what puts those links at the top?

I see something similar for other links
e.g., from
https://www.pyopensci.org/contributing-guide/authoring/index.html
this one 404s
https://www.pyopensci.org/authoring/collaboration.html
but I can go directly to
https://www.pyopensci.org/contributing-guide/authoring/collaboration.html
**--> the "contributing-guide" is what's missing from the links that 404.**

I tried building locally and don't have this problem when I do.

I'm sorry I'm not able to troubleshoot further right now but I wanted to go ahead and let you know about the issue.
Hopefully I'm at least giving you enough info to make it easier to figure out what's going on.

**Comment by lwasser** [comment]
@NickleDave  thank you... i see this is created by this code. we may need @choldgraf here...

Chris -- the issue is that the auto generated TOC at the top of the page is skipping the "contributing-guide" part of the link that is causing the 404. how does that toc element generate links? 

```

```{tableofcontents}
```

```

i see this in the config needs to be updated to contributing-guide

https://github.com/pyOpenSci/contributing-guide/blob/master/_config.yml#L8

the readme is also dated which again is not  causing this issue i think.

https://github.com/pyOpenSci/contributing-guide/blob/master/README.md

i'm not sure how TOC is generated but maybe we can fix it in our meeting this week if people are available? i was thinking we'd have another working meeting to talk about things like updating docs and then maybe also the newest reviews underway.

**Comment by choldgraf** [comment]
hmmmm - I think this one might be fixed in the `master` branch of jupyter-book. Any chance somebody wants to try building the site w/ master and seeing if it works? :-)

**Comment by NickleDave** [comment]
when I build locally with jupyter-book 0.7.1 and view `_build/html` from localhost (using `python -m http.server`) I don't have this issue

but it's because there's no 'contributing-guide' in *any* of the links

I can try with `master` of jupyter-book but not clear to me if that will diagnose the issue

**Comment by lwasser** [comment]
hey @NickleDave following up on this one. i *think* this is working now but i want to double check before i just close it. it seems to be working when i navigate to that page can you kindly confirm?

**Comment by NickleDave** [comment]
Yes, can confirm that the links in both the sidebars and in the bulleted lists at the top of the pages are now working (even though some of the links above still 404 -- I take it the deployed site is no longer using those links). 

Clearly I resolved the issue by forgetting about it (sorry @lwasser)
